export const ActionTypes={
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT" ,
    ADD_TO_CART:"ADD_TO_CART",
    QTY_INCREMENT_PRODUCT:"QTY_INCREMENT_PRODUCT",
    QTY_DECREMENT_PRODUCT:"QTY_DECREMENT_PRODUCT",
    REMOVE_CART_PRODUCT:"REMOVE_CART_PRODUCT",
    IS_USER_LOGIN:"IS_USER_LOGIN",
    IS_USER_LOGOUT:"IS_USER_LOGOUT"     
}